kind: ReplicationController
apiVersion: v1
metadata:
  name: replication-controller
spec:
  replicas: 2
  selector:
    environment: prod
  template:
    metadata:
      name: rc-pod
      labels:
        environment: prod
    spec:
      containers:
       - name: c00
         image: nginx
         command: ["/bin/bash", "-c", "while true; do echo Hello; sleep 5 ; done"]
